force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WeatherInfo__c/WeatherInfo__c.object-meta.xml
<CustomObject>
    <label>WeatherInfo</label>
    <nameField>
        <label>WeatherInfo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WeatherInfos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WeatherInfo__c/fields/Feels_Like__c.field-meta.xml
<CustomField>
    <fullName>Feels_Like__c</fullName>
    <label>Feels Like</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WeatherInfo__c/fields/Icon__c.field-meta.xml
<CustomField>
    <fullName>Icon__c</fullName>
    <label>Icon</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WeatherInfo__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>WeatherInfos</relationshipLabel>
    <relationshipName>WeatherInfos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/WeatherInfo__c/fields/Maximum_Temperature__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Temperature__c</fullName>
    <label>Maximum Temperature</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WeatherInfo__c/fields/Minimum_Temperature__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Temperature__c</fullName>
    <label>Minimum Temperature</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WeatherInfo__c/fields/temperature__c.field-meta.xml
<CustomField>
    <fullName>temperature__c</fullName>
    <label>temperature</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LocationWeatherDisplay.cls
/**
 * @description       : This class is used to display latest weather record on lwc
 * @author            : alainclaudebe@outlook.com
 * @group             : 
 * @last modified on  : 02-05-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/

public with sharing class LocationWeatherDisplay {
    @AuraEnabled(cacheable=true)
    public static List<WeatherInfo__c> getLocationWeatherInfo(Id locationId) {
        return [SELECT Id,
                Icon__c,
                Name,
                Feels_Like__c,
                Maximum_Temperature__c,
                Minimum_Temperature__c,
                Temperature__c,
                Location__r.Name,
                Description__c
                FROM WeatherInfo__c
                WHERE Location__c = :locationId
                ORDER BY CreatedDate DESC
                LIMIT 1
               ];
        
    }
}